{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "matomo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
data:
  config.ini.php: |-
{{ .Values.config.file | indent 4 }}
{{- end -}}