apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matomo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
data:
  ALLOW_EMPTY_PASSWORD: {{ "no" | b64enc }}
  MATOMO_HOST: {{ .Values.matomo.host | b64enc }}
  MATOMO_USERNAME: {{ .Values.matomo.username | b64enc }}
  MATOMO_PASSWORD: {{ .Values.matomo.password | b64enc }}
  MATOMO_EMAIL: {{ .Values.matomo.email | b64enc }}
  MATOMO_WEBSITE_NAME: {{ .Values.matomo.website_name | b64enc }}
  MATOMO_WEBSITE_HOST: {{ .Values.matomo.website_host | b64enc }}
  {{ $app_name :=  include "matomo.fullname" . }}
  {{ $data := dict "Values" .Values.mariadb "Chart" .Chart "Release" .Release }}
  {{ $mariadb_name := include "mariadb.primary.fullname" $data }}
  {{ $mariadb_host := printf "%s-%s" $app_name $mariadb_name }}
  MARIADB_HOST: {{ $mariadb_host | b64enc }}
  MARIADB_PORT_NUMBER: {{ .Values.mariadb.primary.service.port | toString | b64enc }}
  MATOMO_DATABASE_NAME: {{ .Values.mariadb.auth.database | b64enc }}
  MATOMO_DATABASE_USER: {{ .Values.mariadb.auth.username | b64enc }}
  MATOMO_DATABASE_PASSWORD: {{ .Values.mariadb.auth.password | b64enc }}
