apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matomo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
data:
  ALLOW_EMPTY_PASSWORD: {{ "no" | b64enc }}
  MATOMO_HOST: {{ .Values.matomo.host | b64enc }}
  MATOMO_USERNAME: {{ .Values.matomo.username | b64enc }}
  MATOMO_PASSWORD: {{ .Values.matomo.password | b64enc }}
  MATOMO_EMAIL: {{ .Values.matomo.email | b64enc }}
  MATOMO_WEBSITE_NAME: {{ .Values.matomo.website_name | b64enc }}
  MATOMO_WEBSITE_HOST: {{ .Values.matomo.website_host | b64enc }}
  {{ $app_name :=  include "matomo.fullname" . }}
  {{ $mariadb_name := "mariadb" }} {{/* find a way to get the value from "master.fullname" */}}
  {{ $mariadb_host := printf "%s-%s" $app_name $mariadb_name }}
  MARIADB_HOST: {{ $mariadb_host | b64enc }}
  MARIADB_PORT_NUMBER: {{ .Values.mariadb.service.port | toString | b64enc }}
  MATOMO_DATABASE_NAME: {{ .Values.mariadb.db.name | b64enc }}
  MATOMO_DATABASE_USER: {{ .Values.mariadb.db.user | b64enc }}
  MATOMO_DATABASE_PASSWORD: {{ .Values.mariadb.db.password | b64enc }}