{{- if .Values.traefik.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "matomo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.matomo.host }}`)
      kind: Rule
      services:
        - name: {{ include "matomo.fullname" . }}
          port: {{ .Values.service.port }}
  tls:
    certResolver: letsencrypt-tls
{{- end }}